const ADD_EXPERIENCE = {
    ADD_EXPERIENCE: 'Add experience',
    REQUIRED: '* Indicates required',
    TITLE: 'Title*',
    EMP_TYPE: 'Employment type',
    COMPANY: 'Company or organization*',
    CURRENTLY_WORKING: 'I am currently working in this role',
    START_DATE: 'Start date*',
    END_DATE: 'End date*',
    LOCATION: 'Location',
    LOCATION_TYPE: 'Location type',
    DESCRIPTION: 'Description',
    AI_SUGGESTIONS_BOLD: 'Get AI suggestions',
    AI_SUGGESTIONS: ' with Premium',
    AI_ASSISTANCE: 'Unlock AI assistance with 20 words',
    PROFILE_HEADLINE: 'Profile headline',
    HEADLINE_LOCATION: 'Appears below your name at the top of the profile',
    FOUND_JOB: 'Where did you find this job?',
    SEARCH_EXPERIENCE: 'This information will be used to improve LinkedIn\'s job search experience.',
    SKILLS: 'Skills',
    SKILLS_USED: 'We recommend adding your top 5 used in this role. They\'ll also appear in your Skills section.',
    MEDIA: 'Media',
    ADD_MEDIA: 'Add media like images, documents, sites or presentations. Learn more about ',
    ADD_MEDIA_BOLD: 'media file types supported',
}

export { ADD_EXPERIENCE };